# Generated by Django 5.1.8 on 2025-06-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_application', '0002_changetype_change_eventsource_event_maintenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalservice',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='dependent_services', to='business_application.technicalservice'),
        ),
    ]
