# Generated by Django 5.1.8 on 2025-06-25 12:54

import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_application', '0004_incident'),
        ('extras', '0123_journalentry_kind_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
    ]
