# Generated by Django 5.1.8 on 2025-06-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_application', '0005_incident_tags_alter_incident_custom_field_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
