# Generated by Django 5.1.4 on 2025-08-27 14:27

import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_application', '0005_add_pagerduty_templates_system'),
        ('extras', '0122_charfield_null_choices'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='servicedependency',
            name='unique_service_dependency',
        ),
        migrations.AddField(
            model_name='pagerdutytemplate',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='servicedependency',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='servicedependency',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterUniqueTogether(
            name='servicedependency',
            unique_together={('upstream_service', 'downstream_service')},
        ),
    ]
