# Generated by Django 5.1.4 on 2025-11-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_application', '0007_add_event_validity'),
        ('dcim', '0200_populate_mac_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='affected_devices',
            field=models.ManyToManyField(blank=True, related_name='incidents', to='dcim.device'),
        ),
    ]
