# Generated by Django 5.2 on 2025-11-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_application', '0007_add_event_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='pagerduty_dedup_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
