# Generated by Django for business_application plugin

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_application', '0007_add_event_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='pagerduty_dedup_key',
            field=models.CharField(
                blank=True, 
                help_text='PagerDuty deduplication key returned when incident was created', 
                max_length=255, 
                null=True
            ),
        ),
    ]
