# Generated by Django 5.1.4 on 2025-11-27 14:35

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_application', '0008_add_external_workflow'),
        ('extras', '0122_charfield_null_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalworkflow',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
