# Generated by Django for business_application plugin

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_application', '0008_add_pagerduty_dedup_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalservice',
            name='pagerduty_routing_key',
            field=models.CharField(
                blank=True,
                help_text='PagerDuty routing key for this service',
                max_length=255,
                null=True
            ),
        ),
    ]
