# Generated by Django 5.2 on 2025-11-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_application', '0008_add_external_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapplication',
            name='pagerduty_routing_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='pagerduty_dedup_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technicalservice',
            name='pagerduty_routing_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
